---
driver:
  name: vagrant
  network:
    - ["private_network" , {ip: "10.0.2.18"}] 
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
    roles: [acmestatic]
#    network:
#      - ["private_network" , {ip: "10.0.2.19"}]
    run_list:
      - recipe[acme::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      roles: [acmedynamic]
  - name: varnish
    run_list:
     - recipe[acme::varnish]
    verifies:
     inspec_tests:
       - test/smoke/varnichk
    attributes:
  
